---
- name: Get registry DeploymentConfig
  oc_obj:
    namespace: "{{ openshift_hosted_registry_namespace }}"
    state: list
    kind: dc
    name: "{{ openshift_hosted_registry_name }}"
  register: registry_dc

- name: Wait for registry pods
  oc_obj:
    namespace: "{{ openshift_hosted_registry_namespace }}"
    state: list
    kind: pod
    selector: "{% for label, value in registry_dc.results.results[0].spec.selector.iteritems() %}{{ label }}={{ value }}{% if not loop.last %},{% endif %}{% endfor %}"
  register: registry_pods
  until:
  - "registry_pods.results.results[0]['items'] | count > 0"
  # There must be as many matching pods with 'Ready' status True as there are expected replicas
  - "registry_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions') | oo_collect(attribute='status', filters={'type': 'Ready'}) | map('bool') | select | list | count == openshift_hosted_registry_replicas | int"
  delay: 10
  retries: "{{ (600 / 10) | int }}"

- name: Determine registry fsGroup and runAsUser
  set_fact:
    openshift_hosted_registry_fsgroup: "{{ registry_pods.results.results[0]['items'][0].spec.securityContext.fsGroup }}"
    openshift_hosted_registry_runasuser: "{{ registry_pods.results.results[0]['items'][0].spec.containers[0].securityContext.runAsUser }}"

# https://docs.openshift.com/container-platform/3.6/install_config/registry/deploy_registry_existing_clusters.html#registry-non-production-use
- name: Ensure permissions on the hostpath match the pod configuration
  file:
    path: "{{ openshift.hosted.registry.storage.hostpath.path }}"
    state: directory
    owner: "{{ openshift_hosted_registry_runasuser }}"
    group: "{{ openshift_hosted_registry_fsgroup }}"
    mode: "2750"
