---
- name: Create Hosted Resources - openshift_hosted_registry_console
  hosts: oo_first_master
  roles:
  - role: openshift_hosted_registry_console
    when:
    - openshift_hosted_manage_registry | default(true) | bool
    - openshift_hosted_manage_registry_console | default(true) | bool
    - not (openshift_docker_hosted_registry_insecure | default(false)) | bool
